version: '3.8'

services:
  ecu:
    image: car-sim-linux-native-ecu
    build:
      context: .
      dockerfile: ecu/Dockerfile
    user: root
    volumes:
      - ./docker-tmp:/tmp:rw,z
      - ./shared:/shared:Z
    command: ["/app/ecu_entrypoint.sh"]

  validation:
    image: car-sim-linux-native-validation
    build:
      context: .
      dockerfile: validation/Dockerfile
    user: root
    volumes:
      - ./docker-tmp:/tmp:rw,z
      - ./shared:/shared:Z
    depends_on:
      - ecu
    command: ["/app/validator_entrypoint.sh"]

